services:
  - type: web
    name: propulse-sports-portal
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        sync: false # Tells Render to look for this value securely set in your dashboard, or you can hardcode non-sensitive defaults
      - key: DATABASE_URL
        sync: false